import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Maps Lucide icon name strings (as stored in the database) to [IconData].
///
/// The keys are the icon names lowercased and stripped of hyphens/underscores
/// so "Wrench", "wrench", "heart-handshake", "HeartHandshake" all resolve.
///
/// Add any icon that appears in your database here.
const Map<String, IconData> _lucideIconMap = {
  // General / UI
  'activity': LucideIcons.activity,
  'alertcircle': LucideIcons.alertCircle,
  'alerttriangle': LucideIcons.alertTriangle,
  'archive': LucideIcons.archive,
  'award': LucideIcons.award,
  'bell': LucideIcons.bell,
  'bookmark': LucideIcons.bookmark,
  'box': LucideIcons.box,
  'briefcase': LucideIcons.briefcase,
  'building': LucideIcons.building,
  'building2': LucideIcons.building2,
  'calendar': LucideIcons.calendar,
  'camera': LucideIcons.camera,
  'check': LucideIcons.check,
  'checkcheck': LucideIcons.checkCheck,
  'checkcircle': LucideIcons.checkCircle,
  'checkcircle2': LucideIcons.checkCircle2,
  'chevronsupdown': LucideIcons.chevronsUpDown,
  'circle': LucideIcons.circle,
  'circlealert': LucideIcons.circleAlert,
  'circlecheck': LucideIcons.circleCheck,
  'circledollar': LucideIcons.circleDollarSign,
  'circledollarsign': LucideIcons.circleDollarSign,
  'circlehelp': LucideIcons.circleHelp,
  'clipboard': LucideIcons.clipboard,
  'clock': LucideIcons.clock,
  'cloud': LucideIcons.cloud,
  'code': LucideIcons.code,
  'compass': LucideIcons.compass,
  'cpu': LucideIcons.cpu,
  'creditcard': LucideIcons.creditCard,

  // Home / Services
  'bathroomscale': LucideIcons.bathroomScale,
  'bed': LucideIcons.bed,
  'brickswall': LucideIcons.brickWall,
  'brickwall': LucideIcons.brickWall,
  'bug': LucideIcons.bug,
  'car': LucideIcons.car,
  'carfilled': LucideIcons.carFront,
  'carfront': LucideIcons.carFront,
  'carpet': LucideIcons.layoutPanelTop,
  'cog': LucideIcons.cog,
  'construction': LucideIcons.construction,
  'cooking': LucideIcons.cookingPot,
  'cookingpot': LucideIcons.cookingPot,
  'cross': LucideIcons.crosshair,
  'drill': LucideIcons.drill,
  'droplets': LucideIcons.droplets,
  'droplet': LucideIcons.droplet,
  'electricalswitch': LucideIcons.zap,
  'flame': LucideIcons.flame,
  'flowerpot': LucideIcons.flower,
  'flower': LucideIcons.flower,
  'flower2': LucideIcons.flower2,
  'hammer': LucideIcons.hammer,
  'handhelping': LucideIcons.handHelping,
  'handshake': LucideIcons.handshake,
  'heart': LucideIcons.heart,
  'hearthandshake': LucideIcons.heartHandshake,
  'heartpulse': LucideIcons.heartPulse,
  'home': LucideIcons.home,
  'house': LucideIcons.house,
  'layers': LucideIcons.layers,
  'leaf': LucideIcons.leaf,
  'lightbulb': LucideIcons.lightbulb,
  'lock': LucideIcons.lock,
  'mappin': LucideIcons.mapPin,
  'microwave': LucideIcons.microwave,
  'monitor': LucideIcons.monitor,
  'moonstar': LucideIcons.moonStar,
  'mop': LucideIcons.droplets,
  'package': LucideIcons.package,
  'paint': LucideIcons.paintbrush,
  'paintbrush': LucideIcons.paintbrush,
  'paintbucket': LucideIcons.paintBucket,
  'paintroller': LucideIcons.paintRoller,
  'palmtree': LucideIcons.palmtree,
  'pencil': LucideIcons.pencil,
  'pestcontrol': LucideIcons.bug,
  'phone': LucideIcons.phone,
  'pipe': LucideIcons.pipette,
  'pipette': LucideIcons.pipette,
  'plug': LucideIcons.plug,
  'plug2': LucideIcons.plug2,
  'power': LucideIcons.power,
  'printer': LucideIcons.printer,
  'receipt': LucideIcons.receipt,
  'refrigerator': LucideIcons.refrigerator,
  'ruler': LucideIcons.ruler,
  'scissors': LucideIcons.scissors,
  'screwdriver': LucideIcons.screwdriver,
  'settings': LucideIcons.settings,
  'settings2': LucideIcons.settings2,
  'shield': LucideIcons.shield,
  'shieldcheck': LucideIcons.shieldCheck,
  'shower': LucideIcons.showerHead,
  'showerhead': LucideIcons.showerHead,
  'smartphone': LucideIcons.smartphone,
  'sofa': LucideIcons.sofa,
  'sparkles': LucideIcons.sparkles,
  'spraycan': LucideIcons.sprayCan,
  'sprayCan': LucideIcons.sprayCan,
  'star': LucideIcons.star,
  'sun': LucideIcons.sun,
  'tablet': LucideIcons.tablet,
  'thermometer': LucideIcons.thermometer,
  'tool': LucideIcons.wrench,
  'toolbox': LucideIcons.wrench,
  'trash': LucideIcons.trash,
  'trash2': LucideIcons.trash2,
  'tree': LucideIcons.tree,
  'treepine': LucideIcons.treePine,
  'treesdeciduous': LucideIcons.trees,
  'trees': LucideIcons.trees,
  'truck': LucideIcons.truck,
  'tv': LucideIcons.tv,
  'tv2': LucideIcons.tv2,
  'umbrella': LucideIcons.umbrella,
  'user': LucideIcons.user,
  'usercheck': LucideIcons.userCheck,
  'users': LucideIcons.users,
  'utensils': LucideIcons.utensils,
  'utensilscrossed': LucideIcons.utensilsCrossed,
  'walls': LucideIcons.brickWall,
  'washer': LucideIcons.washingMachine,
  'washingmachine': LucideIcons.washingMachine,
  'water': LucideIcons.droplets,
  'wrench': LucideIcons.wrench,
  'zap': LucideIcons.zap,
  'zapoff': LucideIcons.zapOff,
  // category generics
  'layoutgrid': LucideIcons.layoutGrid,
  'grid': LucideIcons.grid2x2,
  'grid2x2': LucideIcons.grid2x2,
  'tag': LucideIcons.tag,
  'tags': LucideIcons.tags,
};

/// Returns the [IconData] for a Lucide icon name string.
///
/// [name] can be any casing — "Wrench", "wrench", "HeartHandshake",
/// "heart-handshake" — all are normalised to lowercase with separators
/// stripped before lookup.
///
/// Falls back to [fallback] (default [LucideIcons.helpCircle]) when
/// [name] is null, empty, or not found in the map.
IconData lucideIconFor(String? name, {IconData fallback = LucideIcons.helpCircle}) {
  if (name == null || name.isEmpty) return fallback;
  // Normalise: strip hyphens, underscores, spaces; lowercase
  final key = name.replaceAll(RegExp(r'[-_\s]'), '').toLowerCase();
  return _lucideIconMap[key] ?? fallback;
}
